name: ReachSMP
version: '1.1.0'
main: com.reachsmp.ReachSMPPlugin
api-version: '1.21'
description: Reach SMP Plugin
authors: [Coolburst/Luconiai]

commands:
  info:
    description: Shows your Reach SMP stats
    usage: /info
  startreachsmp:
    description: Starts the Reach SMP
    usage: /startreachsmp
    permission: reachsmp.admin
  stopreachsmp:
    description: Stops the Reach SMP and removes all variants
    usage: /stopreachsmp
    permission: reachsmp.admin
  fillbar:
    description: Fills your ability bar to 100%
    usage: /fillbar
    permission: reachsmp.admin
  setreach:
    description: Sets your reach variant
    usage: /setreach <variant>
    permission: reachsmp.admin
  setreachlevel:
    description: Sets your reach level
    usage: /setreachlevel <value>
    permission: reachsmp.admin
  reachreload:
    description: Reloads the ReachSMP config
    usage: /reachreload
    permission: reachsmp.admin
  withdraw:
    description: Withdraw 0.5 reach levels into a Reach Bottle
    usage: /withdraw
  giveitem:
    description: Give an item to a player
    usage: /giveitem <item> [amount] [player]
    permission: reachsmp.admin

permissions:
  reachsmp.admin:
    description: Allows admin Reach SMP commands
    default: op
